info:
  contact: {}
paths:
  /event/Delete/{event_id}:
    delete:
      description: Delete event by event ID
      parameters:
      - description: EventUID
        in: path
        name: EventUID
        required: true
        type: string
      responses:
        "204":
          description: No content
        "404":
          description: User not found
          schema:
            type: string
      summary: Delete a event
swagger: "2.0"
